import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "primary-container": "#c8b273",
        "surface-container-high": "#f1e6dd",
        "on-surface": "#1f1b15",
        "outline-variant": "#cec6b5",
        "on-tertiary-container": "#504522",
        "secondary-fixed-dim": "#d3c5a9",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#534410",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f9efe5",
        "on-primary-fixed": "#231b00",
        "on-background": "#1f1b15",
        "error": "#ba1a1a",
        "surface-container": "#f6ece3",
        "primary-fixed-dim": "#dcc584",
        "surface-container-low": "#fcf2e8",
        "tertiary": "#6a5e38",
        "on-tertiary-fixed": "#231b00",
        "on-primary-fixed-variant": "#554511",
        "on-error-container": "#93000a",
        "on-secondary-container": "#6c624a",
        "surface-variant": "#ebe1d7",
        "primary-fixed": "#f9e19d",
        "background": "#fff8f4",
        "secondary": "#675d46",
        "surface-container-highest": "#ebe1d7",
        "surface-dim": "#e2d8cf",
        "on-tertiary-fixed-variant": "#514623",
        "secondary-fixed": "#efe1c4",
        "outline": "#7d7668",
        "on-error": "#ffffff",
        "surface-tint": "#6e5d27",
        "primary": "#6e5d27",
        "tertiary-fixed-dim": "#d6c598",
        "on-surface-variant": "#4b463a",
        "inverse-surface": "#353029",
        "on-secondary-fixed-variant": "#4f4630",
        "inverse-primary": "#dcc584",
        "secondary-container": "#ecdec1",
        "surface-container-lowest": "#ffffff",
        "tertiary-container": "#c3b386",
        "on-secondary-fixed": "#211b09",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#f3e1b2",
        "surface": "#fff8f4",
        "surface-bright": "#fff8f4",
      },
      fontFamily: {
        headline: ["var(--font-serif)", "serif"],
        body: ["var(--font-sans)", "sans-serif"],
        label: ["var(--font-sans)", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
export default config;